### ISSUE TITLE
RestartNextRound It does not work

### ISSUE THREAD

**Issue by SrLicht** [ServerMod/MultiAdmin#232]
As the title says, in the Scopophobia version the restartnextround command does not work and it also takes approximately 5 seconds for a command in MultiAdmin

**Comment by Dankrushen** [comment]
The 5 second delay in commands is most likely due to the new "Idle Mode" in the game, please let me know if this is still the case when the server is not in "Idle Mode."

What version of MultiAdmin are you using?

**Comment by SrLicht** [comment]
3.3.0.0 Test Release

**Comment by Dankrushen** [comment]
There's no consistent round restart message, this should hopefully be fixed in the game soon and won't be a problem anymore, for now, there's nothing I can do
