### ISSUE TITLE
Empty message spammed when game is quit

### ISSUE THREAD

**Issue by RJCooLEST** [ServerMod/MultiAdmin#233]
MultiAdmin 3.2.5:
![image](https://user-images.githubusercontent.com/56374469/89562561-ba201400-d84c-11ea-9037-4a06c42f123f.png)
MultiAdmin 3.3.0.0 - Tester Release:
![image](https://user-images.githubusercontent.com/56374469/89562992-5b0ecf00-d84d-11ea-874c-4fd25cf19dc5.png)

At the end of the server.

but.Fortunately everything is normal.
:)

**Comment by Dankrushen** [comment]
This should've already been fixed by version 3.3.0.1 a couple months ago, I finally got back to working on MultiAdmin last night and got that pushed as a tester release today. Please let me know if you get this behaviour in version 3.3.0.1.

**Comment by RJCooLEST** [comment]
Thx ! Works as I expected.

**Comment by Dankrushen** [comment]
Re-open the issue if it happens again and I can look into it.
