### ISSUE TITLE
Can't use console in pterodactyl panel

### ISSUE THREAD

**Issue by SrLicht** [ServerMod/MultiAdmin#236]
Every time a command is inserted in the ptero terminal, it causes a crash on the server

![image](https://user-images.githubusercontent.com/36207738/91830940-cf088100-ec19-11ea-9a80-f44e05152a67.png)

![image](https://user-images.githubusercontent.com/36207738/91831258-3b838000-ec1a-11ea-9ae9-57999a23bd4b.png)

Startup parameter
![image](https://user-images.githubusercontent.com/36207738/91831330-5229d700-ec1a-11ea-9f9c-12edfaf796cb.png)

**Comment by Dankrushen** [comment]
Your console doesn't seem to support a bunch of console features, using `use_new_input_system: false` should fix the issue. It'd be worthwhile to look into the other available configs, there should be a decent amount to get it working properly on Pterodactyl.

**Comment by Dankrushen** [comment]
Closing, assuming this resolved the issue.
