### ISSUE TITLE
I have a suggestion.

### ISSUE THREAD

**Issue by Tamago4a** [ServerMod/MultiAdmin#240]
I suggest making some kind of setting so that you can ban users on all servers at the same time, and not just on one.

**Comment by moseechev** [comment]
And why would you need that?
How are ya going to connect RA to multiple servers?

**Comment by Dankrushen** [comment]
I don't believe that MultiAdmin is an appropriate place for this feature. It would fit much better as a mod feature, plugin, or to be implemented in the game itself. I'd also like to recommend the option of using the game's query server to issue bans on multiple servers at once.

**Comment by ced777ric** [comment]
Or just share the ban file using the config sharing system, if your servers are on different users or machines you would have to do what Dankrushen said

**Comment by Tamago4a** [comment]
Are you trolling me? I mean, servers on different ports (7777 and 7778) do not have common banned files. Both folders (SCP Secret Laboratory Dedicated Server / servers / 7777-7778 /) contain unique lists of banned players.

**Comment by Dankrushen** [comment]
> Or just share the ban file using the config sharing system, if your servers are on different users or machines you would have to do what Dankrushen said

Ah, yes, I think this is possible, but I wouldn't entirely recommend it since it could cause instability if multiple servers are using it at the same time, you also have to reload the ban file when you ban someone then.

> Are you trolling me? I mean, servers on different ports (7777 and 7778) do not have common banned files. Both folders (SCP Secret Laboratory Dedicated Server / servers / 7777-7778 /) contain unique lists of banned players.

I believe it's a game config.

**Comment by Tamago4a** [comment]
> I believe it's a game config.

I don't quite understand what you mean. After all, it is multiadmin that makes me make 2 separate folders with different files for the ban. Localadmin.exe used a folder in AppData.
