### ISSUE TITLE
rnr kills the server

### ISSUE THREAD

**Issue by Nekonyx** [ServerMod/MultiAdmin#248]
Game: 10.2.1
EXILED: 2.1.18
MultiAdmin: 3.3.1.1

Ready to give further details (e.g. ma/game logs) if needed.

![image](https://user-images.githubusercontent.com/16444061/104106985-8194d280-52e3-11eb-9c76-a91f28907f22.png)

**Comment by Nekonyx** [comment]
Sorry, the problem is clearly not in MultiAdmin, because it does not support short alias (rnr is a base-game command).
But I think that MultiAdmin still incorrectly handles `OutputCodes` from the server.

**Comment by Dankrushen** [comment]
Hm, this is serious issue... I'll have to look into it... (Why isn't there an output code specifically for that??? Or why doesn't it send it when it's actually restarting...)
