### ISSUE TITLE
Logfilesize Ballooning

### ISSUE THREAD

**Issue by ich777** [ServerMod/MultiAdmin#253]
Currently I'm experiencing a huge problem with MultiAdmin.

The server writes a huge log file after 1 or 2 minutes and it's getting bigger and bigger...

![grafik](https://user-images.githubusercontent.com/28066518/106349674-1af64980-62d0-11eb-838b-2a99f4aff3a3.png)

I run MultiAdmin with Mono in a Debian Container for Unraid, please look at the original post here:
https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/?do=findComment&comment=941528

This is a completely fresh install with no mods or anything installed, ~~even tried to disable logging but that was completely ignored...~~ this was my fault now it's creating no log file.
![grafik](https://user-images.githubusercontent.com/28066518/106349720-97892800-62d0-11eb-8ba3-bdbc0df444c6.png)

After writing this message the log has grown again:
![grafik](https://user-images.githubusercontent.com/28066518/106349742-c1dae580-62d0-11eb-8f08-3b2ac168e104.png)

EDIT: Here is the output of the log before it balloons:
![grafik](https://user-images.githubusercontent.com/28066518/106349933-542fb900-62d2-11eb-84c3-e1b023721eff.png)

EDIT2: I implemented a quick and dirty fix that disables the logfile for now.

**Comment by Dankrushen** [comment]
I'm not exactly sure what's going on here? I assume it has to do with how Unraid reads log files, I might look into this but this would be extra work to support it specifically.

**Comment by ich777** [comment]
Why should this be Unraid related?
I forgot to say that I run this in a Docker container that I've created for SCP/Multiadmin: [Click](https://github.com/ich777/docker-steamcmd-server/tree/scp-secretlaboratory)

It's based on Debian Buster, I don't think it's realted to Unraid because I've never had a problem with the container, the user that reported the problem also told me that this was never a problem and it began about one or two weeks ago.
I will test it later if this happens also on my Debian Buster machine.

Has anything changed in the past month or so in terms of the log?

**Comment by Dankrushen** [comment]
I changed the logging slightly, now instead of re-opening a handle for each log individually, it keeps one handle open the whole time and flushes after each message. That should result in essentially the same thing.

I'm assuming it's related to how you're reading the file that is causing the issue?

**Comment by ich777** [comment]
I don't read the file, the first screenshot is from the output of the console.

I think it outputs 'unexpected EOF' because it's getting this big (also the last screenshot is from what the log looks like if you open up the file right after the start of the container and nothing more is displayed, after that it begins to balloon).

This is really weired, have to try it on a native Debian Machine...

**Comment by Dankrushen** [comment]
Where is the error coming from, though? That doesn't look like a MultiAdmin error to me unless I'm not remembering correctly... I'll look and see if that's anywhere in MultiAdmin, but I don't think it is.

**Comment by Dankrushen** [comment]
It looks like it's coming from Docker itself https://github.com/moby/moby/issues/35370

I'm not quite sure what Docker is expecting, if you have any idea, then I would be open to hearing it, but for now I'll look into it a bit myself...

**Comment by ich777** [comment]
@Dankrushen tried it now an a native Debian Machine with the same result the logfile is ballooning again and I can't even type something in the console and is completely unresponsive...

Here is a screenshot from the file when I open it, right after the start of the Server:
![1](https://user-images.githubusercontent.com/28066518/107074729-6c7b6880-67e9-11eb-867d-67f40477e122.png)


Here is a screenshot from the size after about 1 minute of runtime:
![2](https://user-images.githubusercontent.com/28066518/107074797-8321bf80-67e9-11eb-9838-ea4f03f90dc9.png)


And here is a screenshot from the console, again, completely unresponsive, CTRL+C works after about 30 seconds:
![3](https://user-images.githubusercontent.com/28066518/107074864-9df43400-67e9-11eb-9c51-7768a5e0fb40.png)

**Comment by ich777** [comment]
The server runs but it balloons the logfilesize completely and about after 10 minutes it's about 10GB in size.

**Comment by ich777** [comment]
Can it be that this is also related to #254 ?

**Comment by Dankrushen** [comment]
You're running an outdated version of MultiAdmin, I'm only taking issues for MultiAdmin v3.3.1.0 and higher

**Comment by ich777** [comment]
@Dankrushen these are marked as 'pre releases' and my container grabs only always the 'latest' release from your repo but I could update too to see if it solves the issue...

**Comment by Dankrushen** [comment]
They are indeed pre-relases since they are somewhat unstable (as can be seen from the influx of issues). I'm guessing that's most likely your problem. MultiAdmin versions under MultiAdmin v3.3.1.0 won't be able to run the latest version of the game.

**Comment by ich777** [comment]
Yes, this solves the issue why aren't the new releases marked as latest?

Should I change the container script to pull always the latest version regardless if it's the latest or a pre release?

One thing is that the server is indeed running with a older version but the logfile is ballooning.

**Comment by Dankrushen** [comment]
This should _hopefully_ be an uncommon occurrance, since it was the game that changed the message protocol in a way that breaks MultiAdmin. There will be a new latest release once it's stable, for now it's simply a pre-relase.

> One thing is that the server is indeed running with a older version but the logfile is ballooning.

What I mean is that the older version of MultiAdmin isn't able to properly read the server's messages and would allocate huge amounts of memory because the number of bytes it expects is incorrect, therefore crashing the console and potentially bloating the log files with corrupt data.

**Comment by ich777** [comment]
Thank you for you assistance @Dankrushen and clarification!
For now I changed the container to always pull the latest available release regardless if it's a pre release or release version.

**Comment by Dankrushen** [comment]
All good, I should've double checked that you were on the right version.
